workflows:
  androidtv_sample_inputs:
    name: Build AndroidTV Sample Inputs
    max_build_duration: 60 # Max duration of the build in minutes
    environment:
      vars:
        PROJECT_DIR: "InputSample" # Specify the directory containing the Android project
    scripts:
      - name: Install Dependencies
        script: |
          cd $PROJECT_DIR
          ./gradlew dependencies
      - name: Build AAR
        script: |a
          cd $PROJECT_DIR
          ./gradlew assembleRelease # Or the specific task you want to run
    artifacts:
      - build/outputs/**/*.apk
      - build/outputs/**/*.aar
