name: Build AndroidTV Sample Inputs Library

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: library # Directory containing the library code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Gradle 7.0.2
        run: |
          wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
          unzip gradle-7.0.2-bin.zip -d $HOME
          echo "$HOME/gradle-7.0.2/bin" >> $GITHUB_PATH # Add the new Gradle to the PATH

      - name: Install Android SDK Command Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

      - name: Set up Android SDK
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Library with Gradle
        run: gradle :library:build # Use the newly installed Gradle version

      - name: Archive build outputs
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: library/build/outputs/**/* # Path to AAR outputs